### ISSUE TITLE
Dataset Download Error

### ISSUE THREAD

**Issue by QYixuan** [BCV-Uniandes/GraSP#2]
Hi,

Thank you for your great work! When I tried to download the dataset using $wget -r http://157.253.243.19/GraSP, it failed all the time. It showed 'Unkown error' and I can not solve it.
![1717593666695](https://github.com/BCV-Uniandes/GraSP/assets/140317164/4ff745e8-304d-4edd-9f47-41f0cbcae1f9)

Could you please provde another valid download link or dataset comprassed pacakage? Thanks :)

**Comment by nayobi** [comment]
Hello, we have modified our download links. You can now download a compressed archive with wget or from the provided Google Drive link. Please check the updated download instructions in the README file and let us know if you still have trouble.
