### ISSUE TITLE
Unable to download dataset

### ISSUE THREAD

**Issue by zaidbhat1234** [BCV-Uniandes/GraSP#3]
I am unable to download the dataset directly from your server using the link:
`wget http://157.253.243.19/GraSP/<file_name>`.

I get the following error: 
`Connecting to 157.253.243.19:80... failed: Connection refused.`.

**Comment by nayobi** [comment]
Hello

We've been having some trouble with our servers, so we have now uploaded the entire dataset into the Google Drive link provided in the README file.
