### ISSUE TITLE
The function xywhbbox_to_dxdydxdybbox is missing from tapis.evaluate.utils.

### ISSUE THREAD

**Issue by 1170300714** [BCV-Uniandes/GraSP#4]
Hello, when I running your code,  it raise:

Traceback (most recent call last):
  File "tools/run_net.py", line 9, in <module>
    from train_net import train
  File "/GraSP/TAPIS/tools/train_net.py", line 22, in <module>
    from tapis.utils.meters import EpochTimer, SurgeryMeter
  File "/GraSP/TAPIS/tapis/utils/meters.py", line 18, in <module>
    import tapis.evaluate.main_eval as grasp_eval
  File "/GraSP/TAPIS/tapis/evaluate/main_eval.py", line 11, in <module>
    from .detection_eval import eval_detection
  File "/GraSP/TAPIS/tapis/evaluate/detection_eval.py", line 15, in <module>
    from .utils import xywhbbox_to_dxdydxdybbox as normalize_bbox
ImportError: cannot import name 'xywhbbox_to_dxdydxdybbox' from 'tapis.evaluate.utils' (/GraSP/TAPIS/tapis/evaluate/utils.py)

Maybe the function  "xywhbbox_to_dxdydxdybbox"   is missing from tapis.evaluate.utils

Could you release the code of this function?

Thanks a lot!

**Comment by nayobi** [comment]
Hello.

Thank you very much for reporting this. It seems like this function was accidentally deleted while commenting on the functions on that file in a recent commit. 
We have already corrected this mistake in the latest commit. Thank you very much, and please let us know if you encounter any other issues.

**Comment by 1170300714** [comment]
收到，感谢您的来件
